baseURL = 'https://arnovdh.be/'
languageCode = "en-us"
title = "Arno's blog"
theme = "notrack"
# newContentEditor = "nvim"
mainSections = ["blog"]
# disqusShortname = "example"
paginate = 8

[params]
  author = "Arno"
  siteHeading = "Arno" # defaults to author
  favicon = "hugo_grotius.png" # Adds a small icon next to the page title in a tab
  showBlogLatest = true
  mainSections = ["blog"]
  showTaxonomyLinks = false
  nBlogLatest = 5 # number of blog post om the home page
  blogLatestHeading = "My latest blogposts"
  footer = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License" # Made with Hugo - Notrack theme by Simon Bengtsson

  [params.social]
    email = "arno.vandenhende@posteo.net"
    mastodon = "mysteriarch"
    goodreads = "arnovdh"
    steam = "thorontur"
    rss = ""

[taxonomies]
  year = "year"
  month = "month"
  tags = "tags"
  categories = "categories"

[permalinks]
  blog = "/blog/:year/:slug"
